#!/usr/bin/env node
/**
 * Generates src/data/scripture.generated.ts from the bundled scripture datasets.
 *
 * Each dataset (bible / quran / torah) lives under assets/data/<dataset>/ as a set
 * of per-book JSON files plus an index.json that lists books grouped by testament.
 * Metro cannot resolve require() with a dynamic path, so we statically emit a lazy
 * import() loader for every book file. This keeps each book in its own async chunk
 * (code-split on web, lazy on native) instead of eagerly bundling ~5 MB of text.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DATA_DIR = join(ROOT, 'assets', 'data');

const DATASETS = [
  { id: 'bible', title: 'Bible', subtitle: 'King James Version', rootKey: 'bible' },
  { id: 'quran', title: 'Quran', subtitle: 'English', rootKey: 'quran' },
  { id: 'torah', title: 'Torah', subtitle: 'English', rootKey: 'torah' },
];

const escape = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

let loaderLines = [];
let datasetEntries = [];

for (const ds of DATASETS) {
  const dir = join(DATA_DIR, ds.id);
  const index = JSON.parse(readFileSync(join(dir, 'index.json'), 'utf8'));
  // index.json always uses the "bible" root key (quirk of the source data),
  // with testament[] -> book[] -> @attributes.name
  const testaments = (index.bible?.testament ?? []).map((t) => ({
    name: t['@attributes']?.name ?? '',
    books: (t.book ?? []).map((b) => b['@attributes']?.name).filter(Boolean),
  }));

  // Confirm every listed book has a matching file; warn otherwise.
  const files = new Set(readdirSync(dir).filter((f) => f.endsWith('.json') && f !== 'index.json'));
  // Map trimmed basename -> actual filename, to tolerate trailing/leading
  // whitespace differences between index.json names and on-disk filenames.
  const byTrimmed = new Map();
  for (const f of files) byTrimmed.set(f.replace(/\.json$/, '').trim(), f);

  for (const t of testaments) {
    for (const book of t.books) {
      let file = `${book}.json`;
      if (!files.has(file)) {
        const alt = byTrimmed.get(book.trim());
        if (!alt) {
          console.warn(`[gen-data] WARN ${ds.id}: missing file for book "${book}"`);
          continue;
        }
        file = alt;
      }
      const key = `${ds.id}/${book}`;
      loaderLines.push(
        `  '${escape(key)}': () => import('../../assets/data/${ds.id}/${escape(file)}'),`
      );
    }
  }

  datasetEntries.push(
    `  ${ds.id}: {\n` +
      `    id: '${ds.id}',\n` +
      `    title: '${escape(ds.title)}',\n` +
      `    subtitle: '${escape(ds.subtitle)}',\n` +
      `    rootKey: '${ds.rootKey}',\n` +
      `    testaments: ${JSON.stringify(testaments)},\n` +
      `  },`
  );
}

const out = `// AUTO-GENERATED by scripts/gen-data.mjs — do not edit by hand.
// Run \`npm run gen:data\` to regenerate.
/* eslint-disable */

export type Testament = { name: string; books: string[] };
export type DatasetId = 'bible' | 'quran' | 'torah';
export type ScriptureDataset = {
  id: DatasetId;
  title: string;
  subtitle: string;
  rootKey: string;
  testaments: Testament[];
};

export type Chapter = { number: string; verses: string[] };

export const SCRIPTURES: Record<DatasetId, ScriptureDataset> = {
${datasetEntries.join('\n')}
};

// Lazy per-book loaders keyed by "<dataset>/<book>".
const LOADERS: Record<string, () => Promise<any>> = {
${loaderLines.join('\n')}
};

/** Loads and normalizes a book into an ordered list of chapters. */
export async function loadBook(dataset: DatasetId, book: string): Promise<Chapter[]> {
  const loader = LOADERS[\`\${dataset}/\${book}\`];
  if (!loader) throw new Error(\`Unknown book: \${dataset}/\${book}\`);
  const mod = await loader();
  const raw = (mod && mod.default) || mod;
  const rootKey = SCRIPTURES[dataset].rootKey;
  const root = raw[rootKey] ?? raw.bible ?? raw.quran ?? raw.torah ?? raw;
  const testaments = root?.testament ?? [];
  for (const t of testaments) {
    for (const b of t.book ?? []) {
      if (b?.['@attributes']?.name === book || (t.book?.length === 1)) {
        return (b.chapter ?? []).map((c: any) => ({
          number: c?.['@attributes']?.number ?? '',
          verses: Array.isArray(c?.verse) ? c.verse : [c?.verse].filter(Boolean),
        }));
      }
    }
  }
  return [];
}
`;

writeFileSync(join(ROOT, 'src', 'data', 'scripture.generated.ts'), out, 'utf8');
console.log(
  `[gen-data] wrote src/data/scripture.generated.ts (${loaderLines.length} books across ${DATASETS.length} datasets)`
);
